version: "3"
services:
  bird-bot:
    container_name: "bird-bot"
    build:
      dockerfile: "Dockerfile"
      context: "."
    environment:
      # Your bots token
      - TOKEN=
      # Port for api to bind.
      - PORT=5000
      # The full FQDN (https://api.api.com or http://api.api.com:5000)
      - FQDN=https://
    ports:
      - ${PORT}:${PORT}
    volumes:
      - db:/usr/src/bot/data
    restart: unless-stopped

volumes:
  db:
